<?php
$headerHtml = "";
$this->display("section/header.phtml", array("headerHtml" => $headerHtml));
?>
<?php $this->display("section/left.phtml"); ?>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">

        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row" style="min-height:400px;margin: 10px">

            </div>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
<?php $this->display("section/footer.phtml"); ?>
